# Generated by Django 5.0.1 on 2024-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('file_path', models.TextField()),
                ('status', models.CharField(choices=[('done', 'Done'), ('error', 'Error'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='pending', max_length=100)),
                ('vocal_path', models.TextField(blank=True, null=True)),
                ('instrumental_path', models.TextField(blank=True, null=True)),
                ('clone_path', models.TextField(blank=True, null=True)),
                ('cover_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClonedRecord',
        ),
        migrations.DeleteModel(
            name='CoverRecord',
        ),
        migrations.DeleteModel(
            name='SplitRecord',
        ),
    ]
