# Generated by Django 5.0.1 on 2024-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0002_record_delete_clonedrecord_delete_coverrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TTS",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Done"),
                            ("error", "Error"),
                            ("pending", "Pending"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("voice_path", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
