# Generated by Django 4.1.7 on 2024-02-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0005_alter_record_status_alter_tts_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("deleted", "deleted"),
                    ("canceled", "canceled"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tts",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("error", "error"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("deleted", "deleted"),
                    ("canceled", "canceled"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
    ]
