# Generated by Django 4.1.7 on 2024-02-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0006_alter_record_status_alter_tts_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_type", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("waiting_time_in_seconds", models.IntegerField()),
            ],
        ),
    ]
