# Generated by Django 5.0.1 on 2024-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0007_processrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count_cover", models.IntegerField()),
                ("count_tts", models.IntegerField()),
                ("count_split", models.IntegerField()),
                ("count_split_old", models.IntegerField()),
                ("count_clone", models.IntegerField()),
            ],
            options={
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистика",
            },
        ),
    ]
