# Generated by Django 5.0.1 on 2024-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0008_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="average_waiting",
            field=models.IntegerField(default=0),
        ),
    ]
