# Generated by Django 5.0.1 on 2024-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0009_statistics_average_waiting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="average_waiting",
            field=models.CharField(max_length=256),
        ),
    ]
