# Generated by Django 5.1.2 on 2024-10-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0010_alter_statistics_average_waiting"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="denoised_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
