# Generated by Django 5.1.2 on 2024-10-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0011_record_denoised_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="count_denoise",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
