# Generated by Django 5.0.1 on 2024-01-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RVCModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название модели"),
                ),
                ("file", models.FileField(upload_to="", verbose_name="Файл модели")),
            ],
            options={
                "verbose_name": "RVC модель",
                "verbose_name_plural": "RVC модели",
            },
        ),
    ]
