# Generated by Django 5.0.1 on 2024-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rvc", "0002_alter_rvcmodel_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rvcmodel",
            name="name",
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="en",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название EN"
            ),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="es",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название ES"
            ),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="fr",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название FR"
            ),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="hi",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название HI"
            ),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="hide",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="icons", verbose_name="Изображение"
            ),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="ko",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название KO"
            ),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="lock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="pt",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название PT"
            ),
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="ru",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название RU"
            ),
        ),
    ]
