# Generated by Django 5.0.1 on 2024-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvc', '0004_rvcmodel_lang_rvcmodel_speaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rvcmodel',
            options={'ordering': ('order',), 'verbose_name': 'RVC модель', 'verbose_name_plural': 'RVC модели'},
        ),
        migrations.AddField(
            model_name='rvcmodel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
