# Generated by Django 5.0.1 on 2024-02-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvc', '0005_alter_rvcmodel_options_rvcmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvcmodel',
            name='lang',
            field=models.CharField(blank=True, choices=[('ru', 'Ru'), ('de', 'De'), ('en', 'En'), ('es', 'Es'), ('fr', 'Fr'), ('hi', 'Hi'), ('it', 'It'), ('ja', 'Ja'), ('ko', 'Ko'), ('pl', 'Pl'), ('pt', 'Pt'), ('tr', 'Tr'), ('zh', 'Zh')], max_length=128, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='rvcmodel',
            name='speaker',
            field=models.CharField(blank=True, choices=[('0', 'Null'), ('1', 'One'), ('2', 'Two'), ('3', 'Fre'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine')], max_length=128, null=True, verbose_name='Спикер'),
        ),
    ]
