# Generated by Django 5.0.1 on 2024-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvc', '0006_alter_rvcmodel_lang_alter_rvcmodel_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvcmodel',
            name='lang',
            field=models.CharField(blank=True, choices=[('ru', 'ru'), ('de', 'de'), ('en', 'en'), ('es', 'es'), ('fr', 'fr'), ('hi', 'hi'), ('it', 'it'), ('ja', 'ja'), ('ko', 'ko'), ('pl', 'pl'), ('pt', 'pt'), ('tr', 'tr'), ('zh', 'zh')], max_length=128, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='rvcmodel',
            name='speaker',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=128, null=True, verbose_name='Спикер'),
        ),
    ]
