# Generated by Django 4.1.7 on 2024-02-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rvc", "0007_alter_rvcmodel_lang_alter_rvcmodel_speaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Вводите тут название типа app_tts или app_clone",
                        max_length=256,
                        verbose_name="Название проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="en",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="es",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="fr",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="hi",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="hide",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="image",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="ko",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="lock",
        ),
        migrations.RemoveField(
            model_name="rvcmodel",
            name="pt",
        ),
        migrations.AddField(
            model_name="rvcmodel",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ru", "ru"),
                    ("de", "de"),
                    ("en", "en"),
                    ("es", "es"),
                    ("fr", "fr"),
                    ("hi", "hi"),
                    ("it", "it"),
                    ("ja", "ja"),
                    ("ko", "ko"),
                    ("pl", "pl"),
                    ("pt", "pt"),
                    ("tr", "tr"),
                    ("zh", "zh"),
                ],
                max_length=128,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="rvcmodel",
            name="ru",
            field=models.CharField(max_length=256, null=True, verbose_name="Название"),
        ),
        migrations.CreateModel(
            name="RVCModelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Названия для выбора в проекте"
                    ),
                ),
                ("ru", models.CharField(max_length=256, verbose_name="Название RU")),
                (
                    "en",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Название EN",
                    ),
                ),
                (
                    "es",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Название ES",
                    ),
                ),
                (
                    "pt",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Название PT",
                    ),
                ),
                (
                    "fr",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Название FR",
                    ),
                ),
                (
                    "hi",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Название HI",
                    ),
                ),
                (
                    "ko",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Название KO",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="icons",
                        verbose_name="Изображение",
                    ),
                ),
                ("lock", models.BooleanField(default=False)),
                ("hide", models.BooleanField(default=False)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_info",
                        to="rvc.rvcmodel",
                        verbose_name="RVC модель",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rvc.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание модели",
                "verbose_name_plural": "Описания моделей",
                "ordering": ("order",),
            },
        ),
    ]
