# Generated by Django 4.1.7 on 2024-02-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rvc", "0009_remove_rvcmodelinfo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rvcmodel",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("woman", "Женщина"), ("man", "Мужчина")],
                max_length=128,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
