# Generated by Django 4.1.7 on 2024-02-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rvc", "0010_alter_rvcmodel_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="rvcmodelinfo",
            name="audio_example",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="audio_examples",
                verbose_name="Пример аудио",
            ),
        ),
    ]
