# Generated by Django 5.0.1 on 2024-06-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rvc", "0012_category_rvcmodelinfo_created_at_rvcmodelinfo_usages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelProjectUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.BigIntegerField()),
                ("project_id", models.BigIntegerField()),
                ("usages", models.BigIntegerField()),
            ],
        ),
    ]
